### ISSUE TITLE
Inline with needs of vinyl-sourcemap, etc

### ISSUE THREAD

**Issue by phated** [jonschlinkert/file-normalize#1]
@jonschlinkert This is awesome.  I was just looking for replacements for `detect-newline` and `strip-bom` and I find you created said replacements 3 years ago.  So many ❤️ s

**Comment by phated** [comment]
Side note: could you do a review pass on this and bump?

**Comment by jonschlinkert** [comment]
ha, well thanks! no problem. I'll try to do it this evening if possible

**Comment by jonschlinkert** [comment]
@phated sorry for the delay. I've been reviewing [fs-utils](https://github.com/jonschlinkert/fs-utils) alongside this project, trying to decide if I should reallocate some of the utils from fs-utils to this lib to reduce overlap. Any thoughts or opinions on that, or any utils in fs-utils that would be useful here? 

edit: btw, have you seen [update](https://github.com/update/update)? It runs on bach and some of your other libs. Thought I'd mention it, b/c I use it when updating all of these libs. All of the [changes in this one commit on the dev branch](https://github.com/jonschlinkert/file-normalize/pull/2#issue-211740070) were from running the `update` command once.

**Comment by phated** [comment]
Sorry. I just had a chance to look at this.  I don't see any extra things I'd need (currently using a remove-trailing-slash utility in vinyl but don't want all of this for that); however, I think that some of those utilities fit what this module does.

I've been keeping an eye on `update` but haven't tried it nor seen it in action until you posted that PR.  I should really spend some time creating an updater for my stuff (though most of it is done now, haha).

**Comment by jonschlinkert** [comment]
sounds good, I'll get this tidied up and merged.

**Comment by phated** [comment]
@jonschlinkert it actually looks like the EOL stuff done in here is different from `detect-newline` which attempts to figure out which newline is used and use the same one.

**Comment by jonschlinkert** [comment]
It's funny you bring that up, I noticed the same thing after looking at this lib and fs-utils. That was one of the things I was going to tweak here. Sorry had a crazy week, we had a Board meeting today

**Comment by phated** [comment]
All good! I haven't dug into the pieces that will use this library yet.

**Comment by phated** [comment]
@jonschlinkert Maybe we need a utility that appends 2 strings but uses the newline that already exists or something similar?

**Comment by jonschlinkert** [comment]
sorry I cleared this on my phone then forgot to respond! 

> Maybe we need a utility that appends 2 strings but uses the newline that already exists or something similar?

Makes sense, basically just use the EOL that's consistent with what's already being used. We're thinking along the same lines, I'm pretty sure that's in one of the utils, but if not I know a couple of the utils do something very similar and one of them should be made to do exactly this.

what are your thoughts on what to do when EOL was already inconsistent in the user's contents, like when a file is edited by multiple people, etc?  Probably uncommon but also the kind of case that will show up in bug reports when it does happen.  I think the solution is just whatever decision you think would be best for what you're doing.

I can't think of anything besides these bullets, let me know if I'm totally off-mark:

- [x] use the existing EOL to join the strings if one exists
- [ ] if one doesn't exist (like when multiple single line strings are joined) we could either/or: 
  * use the `os.EOL` by default 
  * or, just use newlines (since windows equally supports carriage returns or newlines, and there wasn't one defined already by the user) 
  * or, allow the user to specify EOL to use

**Comment by jonschlinkert** [comment]
as a side note, I've been cringing a lot looking at some of this old code that I wrote lol. makes me happy and sad at the same time lol

**Comment by phated** [comment]
@jonschlinkert those bullets look good.  Could it handle buffer and non-buffer contents on both arguments?  We do a bunch of that juggling, which is annoying.

**Comment by phated** [comment]
An aside: I'm getting very close to needing these utilities.

**Comment by jonschlinkert** [comment]
I'll get moving on this

**Comment by jonschlinkert** [comment]
> Could it handle buffer and non-buffer contents on both arguments? We do a bunch of that juggling, which is annoying.

Sorry @phated, I missed this question.

Meaning, just ensure the value is a string? Or would you want to detect which, and if it's a buffer, convert it to a string - do stuff to it - then return as a buffer?

Either is fine with me and would be fairly trivial to do.

**Comment by phated** [comment]
We have to do stuff like this:

```js
var contents = file.contents.toString() // because it is a buffer
var newline = detectNewline(contents); // Wondering if the newline can be detected without converting from a buffer
var comment = getSourceMapComment() + newline;
var newContents = Buffer.concat([file.contents, new Buffer(comment)]);
file.contents = newContents;
```

But I'd like to do:

```js
file.contents = append(file.contents, comment); // detects newline, appends string or buffer contents together and adds a newline, returns the type of the first value (whether it was a string or buffer)
// Inferring the return type might be bad, maybe it should be `appendString` and `appendBuffer`?
```

**Comment by jonschlinkert** [comment]
we could use `Buffer.indexOf()` to detect the newline. This wasn't introduced until node 1.x (I think) but [there are polyfills](https://github.com/sarosia/buffer-indexof-polyfill).

```js
function appendBuffer(buf, suffix) {
  var eol = new Buffer(buf.indexOf('\r') !== -1 ? '\r\n' : '\n');
  return Buffer.concat([buf, eol, new Buffer(suffix)]);
}
```

edit: the above code would allow `suffix` to be passed as a buffer or string. But we can do a check on the args to ensure they are buffers first.

**Comment by phated** [comment]
Close, but eol comes after suffix because there's already a eol on the buf. Sorry, on my phone. 

Hurray for polyfills.

**Comment by phated** [comment]
Just following up here.

**Comment by jonschlinkert** [comment]
sorry I didn't see that previous comment of yours. 

> but eol comes after suffix because there's already a eol on the buf.

Oh I see, I missed that. I thought you were saying to join with. Should we only add eol if one doesn't already exist?

**Comment by phated** [comment]
I believe the desire is to put an EOL at the end of the sourcemap if the file had an EOL at the end of the file before inserting the sourcemap.  If the file doesn't have an EOL, the sourcemap should probably be appended with `os.eol` but __no__ EOL should be inserted __after__ the sourcemap.

**Comment by doowb** [comment]
Just read through these comments... would the `appendBuffer` look more like this?

```js
var newline = new Buffer('\r\n');
function appendBuffer(buf, suffix) {
  var eol = new Buffer(buf.slice(-2) === newline ? '\r\n' : '\n');
  return Buffer.concat([buf, new Buffer(suffix), eol]);
}
```

It seems like this will achieve the results you're looking for.

**Comment by jonschlinkert** [comment]
good idea with just comparing the buffers. that eliminates the need for `Buffer.indexOf()`

```js
function appendBuffer(buf, suffix) {
  var cr = new Buffer('\r\n');
  var eol = buf.slice(-2) === cr ? cr : new Buffer('\n');
  return Buffer.concat([buf, new Buffer(suffix), eol]);
}
```
edit: but actually we'd need to check for `\n` or `\r\n` before appending either, correct?  So maybe something more like this?

```js
function appendBuffer(buf, suffix) {
  var cr = new Buffer('\r\n');
  var nl = new Buffer('\n');
  var contents = [buf, new Buffer(suffix)];

  if (buf.slice(-2) === cr) {
    contents.push(cr);
  } else if (buf.slice(-1) === nl) {
    contents.push(nl);
  }
  
  return Buffer.concat(contents);
}
```

**Comment by doowb** [comment]
here we go:

```js
var os = require('os');
var equals = require('buffer-equal');

var cr = new Buffer('\r\n');
var nl = new Buffer('\n');

function append(prefix, suffix) {
  if (Buffer.isBuffer(prefix)) {
    return appendBuffer(prefix, suffix);
  }
  return appendString(prefix, suffix);
}

function appendString(str, suffix) {
  var eol;
  if (str.slice(-2) === '\r\n') {
    eol = '\r\n';
  } else if (str.slice(-1) === '\n') {
    eol = '\n';
  } else {
    return [str, os.EOL, suffix].join('');
  }
  return [str, suffix, eol].join('');
}

function appendBuffer(buf, suffix) {
  var eol;
  if (equals(buf.slice(-2), cr)) {
    eol = cr;
  } else if (equals(buf.slice(-1), nl)) {
    eol = nl;
  } else {
    return Buffer.concat([buf, new Buffer(os.EOL), new Buffer(suffix)]);
  }
  return Buffer.concat([buf, new Buffer(suffix), eol]);
}

console.log('buffer with \\r\\n:', [append(new Buffer('abc\r\n'), new Buffer('def')).toString()]);
console.log('buffer with \\n:', [append(new Buffer('abc\n'), new Buffer('def')).toString()]);
console.log('buffer without EOL:', [append(new Buffer('abc'), new Buffer('def')).toString()]);

console.log('string with \\r\\n:', [append('abc\r\n', 'def')]);
console.log('string with \\n:', [append('abc\n', 'def')]);
console.log('string without EOL:', [append('abc', 'def')]);
```

**output**
```
buffer with \r\n: [ 'abc\r\ndef\r\n' ]
buffer with \n: [ 'abc\ndef\n' ]
buffer without EOL: [ 'abc\ndef' ]
string with \r\n: [ 'abc\r\ndef\r\n' ]
string with \n: [ 'abc\ndef\n' ]
string without EOL: [ 'abc\ndef' ]
```

`Buffer#equals` wasn't added until node 0.11.13 so we could use [buffer-equal](https://github.com/substack/node-buffer-equal) 

**edit**
ugg... I couldn't look at those nested conditional operators, used `buffer-equal` and added the output

**edit 2**
updated to return early when the EOL is not on the passed in prefix and use the system one between the prefix and suffix (I just understood that part of @phated last comment)
