### ISSUE TITLE
change reference from strip-bom-buffer -> remove-bom-buffer

### ISSUE THREAD

**Issue by ghost** [jonschlinkert/file-normalize#8]
recent pkg upgrades on a gulp4 + vinyl-fs3 install report:
```
	warning vinyl-fs > vinyl-sourcemap > file-normalize > strip-bom-buffer@1.0.1: This package was renamed to remove-bom-buffer, please use that module instead
```
That looks like a very recent change.

Just fyi, here, package.json still contains the 'old' reference

```
...
  "dependencies": {
    "buffer-equal": "^1.0.0",
    "is-buffer": "^1.1.5",
    "normalize-path": "^2.1.1",
    "strip-bom-buffer": "^1.0.0",
    "strip-bom-string": "^1.0.0"
},
...
```

**Comment by doowb** [comment]
@pgnd sorry for the delay in responding. Thanks for pointing out the update. I'll be updating some other things in this module and I'll also get that dependency updated.
