### ISSUE TITLE
appendString/appendBuffer modules

### ISSUE THREAD

**Issue by phated** [jonschlinkert/file-normalize#9]
I was looking through this module and I found that most of the utilizes are their own modules except these 2 methods.  Do you think it would make sense to create modules for each and proxy the abstraction (`.append`) to those modules?

**Comment by phated** [comment]
@jonschlinkert @doowb can you take a look at this?

**Comment by doowb** [comment]
Sorry, we completely missed this. We're out of the office right now but we'll be on this evening.

**Comment by jonschlinkert** [comment]
lol "we're out of the office". We're driving and doing a conf. call lol. But one of us will be back online in a little bit. sorry for not seeing this before

**Comment by doowb** [comment]
@phated I extracted [appendString](https://github.com/doowb/append-string) and [appendBuffer](https://github.com/doowb/append-buffer) and updated here.

**Comment by phated** [comment]
@doowb thanks!!!
